// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// detectEncoding
CharacterVector detectEncoding(StringVector str);
RcppExport SEXP Ruchardet_detectEncoding(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< StringVector >::type str(strSEXP);
    __result = Rcpp::wrap(detectEncoding(str));
    return __result;
END_RCPP
}
