# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' detect encoding of input string
#' @param str input string
#' @return string of encoding 
#' @references \url{https://code.google.com/p/uchardet/}
detectEncoding <- function(str) {
    .Call('Ruchardet_detectEncoding', PACKAGE = 'Ruchardet', str)
}

