# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get encoding information of input string 
#' @param str input string
#' @return string of encoding 
#' @export
getCharEncoding <- function(str) {
    .Call('Ruchardet_getCharEncoding', PACKAGE = 'Ruchardet', str)
}

